# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestExpensesform():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_expensesform(self):
    self.driver.get("https://applert.eu-gb.cf.appdomain.cloud/")
    self.driver.set_window_size(542, 672)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiListItemButton-root:nth-child(4) path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiListItemButton-root:nth-child(4) path").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "EmployeeMail").click()
    self.driver.find_element(By.ID, "EmployeeMail").send_keys("sauce@ibm.mx")
    self.driver.find_element(By.ID, "Date").click()
    self.driver.find_element(By.ID, "Date").click()
    self.driver.find_element(By.ID, "Date").click()
    self.driver.find_element(By.ID, "Date").send_keys("2022-05-25")
    self.driver.find_element(By.ID, "Amount").click()
    self.driver.find_element(By.ID, "Amount").send_keys("200")
    self.driver.find_element(By.ID, "Comment").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-root:nth-child(5) .MuiSvgIcon-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-root:nth-child(5) .MuiSvgIcon-root").click()
    self.driver.find_element(By.ID, "Comment").send_keys("Hola")
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "ICA-option-2").click()
    self.driver.find_element(By.ID, "Type").click()
    self.driver.find_element(By.ID, "Type-option-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
  
